FROM node:latest AS Production

WORKDIR /

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run production:ssr

COPY --from=Production /Build /var/www/Build
