FROM node:latest AS Production

WORKDIR /

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run production:ssr

RUN rm --recursive --force /var/www/build
COPY /Build /var/www/build
RUN node $(find /var/www/build -name server.*.js)