FROM node:latest AS Production

WORKDIR /usr/src

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run production:ssr:analyze

RUN rm --recursive --force /var/www/build

RUN mkdir --parents /var/www/build

RUN cp --recursive /usr/src/Build/static /var/www/build
RUN cp --recursive /usr/src/node_modules /var/www/build