FROM node:latest AS Development

WORKDIR /

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run development

FROM nginx:latest

COPY --from=Development /Build /var/www/Build
COPY /Application/Ship/Utils/Nginx/nginx.conf /etc/nginx/nginx.conf