FROM node:latest as Development

WORKDIR /usr/src

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run development

FROM nginx:latest

RUN rm --recursive --force /var/www/localhost
RUN rm --recursive --force /var/www/html
RUN rm --force /etc/nginx/sites-available/default
RUN rm --force /etc/nginx/sites-enabled/default
RUN rm --force /etc/nginx/sites-available/localhost.conf
RUN rm --force /etc/nginx/sites-enabled/localhost.conf

RUN mkdir --parents /var/www/localhost
RUN mkdir --parents /etc/nginx/sites-available
RUN mkdir --parents /etc/nginx/sites-enabled

COPY --from=Development /usr/src/Build /var/www/localhost
COPY --from=Development /usr/src/Application/Ship/Utils/Nginx/Docker/Development/nginx.conf /etc/nginx/nginx.conf
COPY --from=Development /usr/src/Application/Ship/Utils/Nginx/Docker/Development/sites-available/localhost.conf /etc/nginx/sites-available/localhost.conf

RUN ln --symbolic /etc/nginx/sites-available/localhost.conf /etc/nginx/sites-enabled/localhost.conf

RUN nginx -t