FROM node:latest AS Development

WORKDIR /Application

RUN npm install --global npm@latest

COPY package.json package.json
RUN npm install

COPY . .
RUN npm run development

FROM nginx:latest

RUN rm --recursive --force /var/www/build
RUN mkdir --parents /var/www/build
RUN mkdir --parents /etc/nginx

COPY --from=Development /Application/Build /var/www/build
COPY /Application/Ship/Utils/Nginx/nginx.conf /etc/nginx/nginx.conf